# Generated by Django 5.1.4 on 2026-04-07 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_reset',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
