# Generated by Django 5.1.4 on 2026-04-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_codigo_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_reset_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
