--
-- PostgreSQL database dump
--

\restrict sUiV8wzXisFiQegOiQnnPSXlOz8EREWX6CCBeqVbIHhI0PadrZyfOGfLV65lvxv

-- Dumped from database version 15.15 (Debian 15.15-1.pgdg13+1)
-- Dumped by pg_dump version 17.9 (Debian 17.9-0+deb13u1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: api_categoria; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_categoria (
    id_categoria integer NOT NULL,
    nombre_categoria character varying(50) NOT NULL,
    activo boolean NOT NULL
);


--
-- Name: api_categoria_id_categoria_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_categoria ALTER COLUMN id_categoria ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_categoria_id_categoria_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_clientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_clientes (
    cedula character varying(20) NOT NULL,
    direccion text,
    correo character varying(100),
    nombre_cliente character varying(100) NOT NULL,
    telefono character varying(20),
    compras integer NOT NULL,
    fecha_registro date NOT NULL,
    activo boolean NOT NULL
);


--
-- Name: api_reporte; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_reporte (
    id_reporte integer NOT NULL,
    tipo_reporte character varying(50) NOT NULL,
    fecha timestamp with time zone NOT NULL,
    total_vendido numeric(10,2) NOT NULL
);


--
-- Name: api_reporte_id_reporte_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_reporte ALTER COLUMN id_reporte ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_reporte_id_reporte_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_reporteproductosvendidos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_reporteproductosvendidos (
    id bigint NOT NULL,
    producto_mas_vendido character varying(100) NOT NULL,
    cantidad integer NOT NULL,
    reporte_id integer NOT NULL
);


--
-- Name: api_reporteproductosvendidos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.api_reporteproductosvendidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_reporteproductosvendidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: api_usuarios; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.api_usuarios (
    id_usuario integer NOT NULL,
    contrasena character varying(255) NOT NULL
);


--
-- Name: auditoria_auditlog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auditoria_auditlog (
    id bigint NOT NULL,
    accion character varying(10) NOT NULL,
    modelo character varying(100) NOT NULL,
    objeto_id character varying(50) NOT NULL,
    cambios jsonb,
    fecha timestamp with time zone NOT NULL,
    usuario_id bigint,
    objeto_nombre character varying(255)
);


--
-- Name: auditoria_auditlog_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auditoria_auditlog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auditoria_auditlog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes_clientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clientes_clientes (
    cedula character varying(20) NOT NULL,
    direccion text,
    correo character varying(100),
    nombre_cliente character varying(100) NOT NULL,
    telefono character varying(20),
    compras integer NOT NULL,
    fecha_registro date NOT NULL,
    activo boolean NOT NULL
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: productos_producto; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.productos_producto (
    id_producto integer NOT NULL,
    nombre character varying(100) NOT NULL,
    precio numeric(10,2) NOT NULL,
    stock_total integer NOT NULL,
    stock_minimo integer NOT NULL,
    activo boolean NOT NULL,
    categoria_id integer NOT NULL,
    creado_por_id bigint,
    editado_por_id bigint
);


--
-- Name: productos_producto_id_producto_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.productos_producto ALTER COLUMN id_producto ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_producto_id_producto_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_rol; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_rol (
    id bigint NOT NULL,
    nombre character varying(100) NOT NULL
);


--
-- Name: usuarios_rol_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_rol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_rol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_usuario (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    foto_url character varying(400),
    activo boolean NOT NULL,
    cedula character varying(20),
    rol_id bigint
);


--
-- Name: usuarios_usuario_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_usuario_groups (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: usuarios_usuario_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_usuario_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_usuario ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios_usuario_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usuarios_usuario_user_permissions (
    id bigint NOT NULL,
    usuario_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: usuarios_usuario_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.usuarios_usuario_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_usuario_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ventas_detalleventa; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ventas_detalleventa (
    id_detalle integer NOT NULL,
    cantidad integer NOT NULL,
    precio numeric(10,2),
    producto_id integer NOT NULL,
    venta_id integer NOT NULL,
    CONSTRAINT ventas_detalleventa_cantidad_check CHECK ((cantidad >= 0))
);


--
-- Name: ventas_detalleventa_id_detalle_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ventas_detalleventa ALTER COLUMN id_detalle ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_detalleventa_id_detalle_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ventas_venta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ventas_venta (
    id_venta integer NOT NULL,
    fecha timestamp with time zone NOT NULL,
    cliente_id character varying(20),
    usuario_id bigint,
    total numeric(12,2) NOT NULL,
    efectivo_recibido numeric(12,2),
    metodo_pago character varying(50)
);


--
-- Name: ventas_venta_id_venta_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ventas_venta ALTER COLUMN id_venta ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ventas_venta_id_venta_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: api_categoria; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.api_categoria (id_categoria, nombre_categoria, activo) FROM stdin;
\.


--
-- Data for Name: api_clientes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.api_clientes (cedula, direccion, correo, nombre_cliente, telefono, compras, fecha_registro, activo) FROM stdin;
\.


--
-- Data for Name: api_reporte; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.api_reporte (id_reporte, tipo_reporte, fecha, total_vendido) FROM stdin;
\.


--
-- Data for Name: api_reporteproductosvendidos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.api_reporteproductosvendidos (id, producto_mas_vendido, cantidad, reporte_id) FROM stdin;
\.


--
-- Data for Name: api_usuarios; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.api_usuarios (id_usuario, contrasena) FROM stdin;
\.


--
-- Data for Name: auditoria_auditlog; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auditoria_auditlog (id, accion, modelo, objeto_id, cambios, fecha, usuario_id, objeto_nombre) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add reporte	6	add_reporte
22	Can change reporte	6	change_reporte
23	Can delete reporte	6	delete_reporte
24	Can view reporte	6	view_reporte
25	Can add reporte productos vendidos	7	add_reporteproductosvendidos
26	Can change reporte productos vendidos	7	change_reporteproductosvendidos
27	Can delete reporte productos vendidos	7	delete_reporteproductosvendidos
28	Can view reporte productos vendidos	7	view_reporteproductosvendidos
29	Can add clientes	8	add_clientes
30	Can change clientes	8	change_clientes
31	Can delete clientes	8	delete_clientes
32	Can view clientes	8	view_clientes
33	Can add usuarios	9	add_usuarios
34	Can change usuarios	9	change_usuarios
35	Can delete usuarios	9	delete_usuarios
36	Can view usuarios	9	view_usuarios
37	Can add categoria	10	add_categoria
38	Can change categoria	10	change_categoria
39	Can delete categoria	10	delete_categoria
40	Can view categoria	10	view_categoria
41	Can add rol	11	add_rol
42	Can change rol	11	change_rol
43	Can delete rol	11	delete_rol
44	Can view rol	11	view_rol
45	Can add user	12	add_usuario
46	Can change user	12	change_usuario
47	Can delete user	12	delete_usuario
48	Can view user	12	view_usuario
49	Can add producto	13	add_producto
50	Can change producto	13	change_producto
51	Can delete producto	13	delete_producto
52	Can view producto	13	view_producto
53	Can add clientes	14	add_clientes
54	Can change clientes	14	change_clientes
55	Can delete clientes	14	delete_clientes
56	Can view clientes	14	view_clientes
57	Can add venta	15	add_venta
58	Can change venta	15	change_venta
59	Can delete venta	15	delete_venta
60	Can view venta	15	view_venta
61	Can add detalle venta	16	add_detalleventa
62	Can change detalle venta	16	change_detalleventa
63	Can delete detalle venta	16	delete_detalleventa
64	Can view detalle venta	16	view_detalleventa
65	Can add audit log	17	add_auditlog
66	Can change audit log	17	change_auditlog
67	Can delete audit log	17	delete_auditlog
68	Can view audit log	17	view_auditlog
\.


--
-- Data for Name: clientes_clientes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.clientes_clientes (cedula, direccion, correo, nombre_cliente, telefono, compras, fecha_registro, activo) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	contenttypes	contenttype
5	sessions	session
6	api	reporte
7	api	reporteproductosvendidos
8	api	clientes
9	api	usuarios
10	api	categoria
11	usuarios	rol
12	usuarios	usuario
13	productos	producto
14	clientes	clientes
15	ventas	venta
16	ventas	detalleventa
17	auditoria	auditlog
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-04-01 17:21:20.923986+00
2	contenttypes	0002_remove_content_type_name	2026-04-01 17:21:20.94167+00
3	auth	0001_initial	2026-04-01 17:21:21.075115+00
4	auth	0002_alter_permission_name_max_length	2026-04-01 17:21:21.090292+00
5	auth	0003_alter_user_email_max_length	2026-04-01 17:21:21.099555+00
6	auth	0004_alter_user_username_opts	2026-04-01 17:21:21.108828+00
7	auth	0005_alter_user_last_login_null	2026-04-01 17:21:21.119582+00
8	auth	0006_require_contenttypes_0002	2026-04-01 17:21:21.126096+00
9	auth	0007_alter_validators_add_error_messages	2026-04-01 17:21:21.136829+00
10	auth	0008_alter_user_username_max_length	2026-04-01 17:21:21.1481+00
11	auth	0009_alter_user_last_name_max_length	2026-04-01 17:21:21.157178+00
12	auth	0010_alter_group_name_max_length	2026-04-01 17:21:21.169395+00
13	auth	0011_update_proxy_permissions	2026-04-01 17:21:21.178691+00
14	auth	0012_alter_user_first_name_max_length	2026-04-01 17:21:21.187887+00
15	usuarios	0001_initial	2026-04-01 17:21:21.378159+00
16	admin	0001_initial	2026-04-01 17:21:21.454418+00
17	admin	0002_logentry_remove_auto_add	2026-04-01 17:21:21.47014+00
18	admin	0003_logentry_add_action_flag_choices	2026-04-01 17:21:21.482693+00
19	api	0001_initial	2026-04-01 17:21:21.699975+00
20	api	0002_post	2026-04-01 17:21:21.729313+00
21	api	0003_rename_cliente_clientes_rename_usuario_usuarios	2026-04-01 17:21:21.809103+00
22	api	0004_delete_post	2026-04-01 17:21:21.816206+00
23	api	0005_usuarios_username_alter_usuarios_id_usuario	2026-04-01 17:21:21.853799+00
24	api	0006_remove_usuarios_username	2026-04-01 17:21:21.861553+00
25	api	0007_remove_producto_id_producto_id_producto	2026-04-01 17:21:21.882084+00
26	api	0008_clientes_compras_clientes_fecha_registro	2026-04-01 17:21:21.895214+00
27	api	0009_remove_venta_usuario_detalleventa_precio_and_more	2026-04-01 17:21:21.947602+00
28	api	0010_remove_reporte_venta	2026-04-01 17:21:21.961867+00
29	api	0011_categoria_remove_producto_tipo_producto_activo_and_more	2026-04-01 17:21:22.058856+00
30	api	0012_categoria_activo	2026-04-01 17:21:22.069867+00
31	api	0013_remove_producto_categoria	2026-04-01 17:21:22.090468+00
32	productos	0001_initial	2026-04-01 17:21:22.126801+00
33	api	0014_alter_detalleventa_producto_delete_producto	2026-04-01 17:21:22.142016+00
34	api	0015_clientes_activo	2026-04-01 17:21:22.151809+00
35	api	0016_remove_venta_cliente_delete_detalleventa_and_more	2026-04-01 17:21:22.166785+00
36	auditoria	0001_initial	2026-04-01 17:21:22.214923+00
37	auditoria	0002_auditlog_objeto_nombre	2026-04-01 17:21:22.229005+00
38	auditoria	0003_alter_auditlog_objeto_id	2026-04-01 17:21:22.27389+00
39	clientes	0001_initial	2026-04-01 17:21:22.317888+00
40	productos	0002_remove_producto_cantidad_alter_producto_id_producto_and_more	2026-04-01 17:21:22.332566+00
41	productos	0003_producto_creado_por_producto_editado_por	2026-04-01 17:21:22.37868+00
42	sessions	0001_initial	2026-04-01 17:21:22.428235+00
43	usuarios	0002_remove_usuario_rol	2026-04-01 17:21:22.445035+00
44	usuarios	0003_usuario_cedula	2026-04-01 17:21:22.481685+00
45	usuarios	0004_alter_usuario_cedula	2026-04-01 17:21:22.498654+00
46	usuarios	0005_usuario_rol	2026-04-01 17:21:22.52716+00
47	ventas	0001_initial	2026-04-01 17:21:22.635371+00
48	ventas	0002_venta_total_alter_detalleventa_precio	2026-04-01 17:21:22.661932+00
49	ventas	0003_venta_efectivo_recibido_venta_metodo_pago	2026-04-01 17:21:22.683636+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
\.


--
-- Data for Name: productos_producto; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.productos_producto (id_producto, nombre, precio, stock_total, stock_minimo, activo, categoria_id, creado_por_id, editado_por_id) FROM stdin;
\.


--
-- Data for Name: usuarios_rol; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios_rol (id, nombre) FROM stdin;
\.


--
-- Data for Name: usuarios_usuario; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios_usuario (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined, foto_url, activo, cedula, rol_id) FROM stdin;
\.


--
-- Data for Name: usuarios_usuario_groups; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios_usuario_groups (id, usuario_id, group_id) FROM stdin;
\.


--
-- Data for Name: usuarios_usuario_user_permissions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.usuarios_usuario_user_permissions (id, usuario_id, permission_id) FROM stdin;
\.


--
-- Data for Name: ventas_detalleventa; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.ventas_detalleventa (id_detalle, cantidad, precio, producto_id, venta_id) FROM stdin;
\.


--
-- Data for Name: ventas_venta; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.ventas_venta (id_venta, fecha, cliente_id, usuario_id, total, efectivo_recibido, metodo_pago) FROM stdin;
\.


--
-- Name: api_categoria_id_categoria_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.api_categoria_id_categoria_seq', 1, false);


--
-- Name: api_reporte_id_reporte_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.api_reporte_id_reporte_seq', 1, false);


--
-- Name: api_reporteproductosvendidos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.api_reporteproductosvendidos_id_seq', 1, false);


--
-- Name: auditoria_auditlog_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auditoria_auditlog_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 68, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, false);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 17, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 49, true);


--
-- Name: productos_producto_id_producto_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.productos_producto_id_producto_seq', 1, false);


--
-- Name: usuarios_rol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuarios_rol_id_seq', 1, false);


--
-- Name: usuarios_usuario_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuarios_usuario_groups_id_seq', 1, false);


--
-- Name: usuarios_usuario_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuarios_usuario_id_seq', 1, false);


--
-- Name: usuarios_usuario_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.usuarios_usuario_user_permissions_id_seq', 1, false);


--
-- Name: ventas_detalleventa_id_detalle_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.ventas_detalleventa_id_detalle_seq', 1, false);


--
-- Name: ventas_venta_id_venta_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.ventas_venta_id_venta_seq', 1, false);


--
-- Name: api_categoria api_categoria_nombre_categoria_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_categoria
    ADD CONSTRAINT api_categoria_nombre_categoria_key UNIQUE (nombre_categoria);


--
-- Name: api_categoria api_categoria_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_categoria
    ADD CONSTRAINT api_categoria_pkey PRIMARY KEY (id_categoria);


--
-- Name: api_clientes api_cliente_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_clientes
    ADD CONSTRAINT api_cliente_pkey PRIMARY KEY (cedula);


--
-- Name: api_reporte api_reporte_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_reporte
    ADD CONSTRAINT api_reporte_pkey PRIMARY KEY (id_reporte);


--
-- Name: api_reporteproductosvendidos api_reporteproductosvendidos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_reporteproductosvendidos
    ADD CONSTRAINT api_reporteproductosvendidos_pkey PRIMARY KEY (id);


--
-- Name: api_usuarios api_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_usuarios
    ADD CONSTRAINT api_usuario_pkey PRIMARY KEY (id_usuario);


--
-- Name: auditoria_auditlog auditoria_auditlog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria_auditlog
    ADD CONSTRAINT auditoria_auditlog_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: clientes_clientes clientes_clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes_clientes
    ADD CONSTRAINT clientes_clientes_pkey PRIMARY KEY (cedula);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: productos_producto productos_producto_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_producto
    ADD CONSTRAINT productos_producto_pkey PRIMARY KEY (id_producto);


--
-- Name: usuarios_rol usuarios_rol_nombre_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_rol
    ADD CONSTRAINT usuarios_rol_nombre_key UNIQUE (nombre);


--
-- Name: usuarios_rol usuarios_rol_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_rol
    ADD CONSTRAINT usuarios_rol_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_usuario_id_group_id_4ed5b09e_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_usuario_id_group_id_4ed5b09e_uniq UNIQUE (usuario_id, group_id);


--
-- Name: usuarios_usuario usuarios_usuario_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_user_pe_usuario_id_permission_id_217cadcd_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_user_pe_usuario_id_permission_id_217cadcd_uniq UNIQUE (usuario_id, permission_id);


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: usuarios_usuario usuarios_usuario_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_username_key UNIQUE (username);


--
-- Name: ventas_detalleventa ventas_detalleventa_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ventas_detalleventa
    ADD CONSTRAINT ventas_detalleventa_pkey PRIMARY KEY (id_detalle);


--
-- Name: ventas_venta ventas_venta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ventas_venta
    ADD CONSTRAINT ventas_venta_pkey PRIMARY KEY (id_venta);


--
-- Name: api_categoria_nombre_categoria_00353524_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_categoria_nombre_categoria_00353524_like ON public.api_categoria USING btree (nombre_categoria varchar_pattern_ops);


--
-- Name: api_cliente_cedula_3784ac97_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_cliente_cedula_3784ac97_like ON public.api_clientes USING btree (cedula varchar_pattern_ops);


--
-- Name: api_reporteproductosvendidos_reporte_id_de23fe7a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX api_reporteproductosvendidos_reporte_id_de23fe7a ON public.api_reporteproductosvendidos USING btree (reporte_id);


--
-- Name: auditoria_auditlog_usuario_id_10036f54; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auditoria_auditlog_usuario_id_10036f54 ON public.auditoria_auditlog USING btree (usuario_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: clientes_clientes_cedula_ffa64315_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX clientes_clientes_cedula_ffa64315_like ON public.clientes_clientes USING btree (cedula varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: productos_producto_categoria_id_1fef506a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productos_producto_categoria_id_1fef506a ON public.productos_producto USING btree (categoria_id);


--
-- Name: productos_producto_creado_por_id_6ad29e0b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productos_producto_creado_por_id_6ad29e0b ON public.productos_producto USING btree (creado_por_id);


--
-- Name: productos_producto_editado_por_id_4818f191; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX productos_producto_editado_por_id_4818f191 ON public.productos_producto USING btree (editado_por_id);


--
-- Name: usuarios_rol_nombre_96a030f6_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_rol_nombre_96a030f6_like ON public.usuarios_rol USING btree (nombre varchar_pattern_ops);


--
-- Name: usuarios_usuario_groups_group_id_e77f6dcf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_groups_group_id_e77f6dcf ON public.usuarios_usuario_groups USING btree (group_id);


--
-- Name: usuarios_usuario_groups_usuario_id_7a34077f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_groups_usuario_id_7a34077f ON public.usuarios_usuario_groups USING btree (usuario_id);


--
-- Name: usuarios_usuario_rol_id_b0d64932; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_rol_id_b0d64932 ON public.usuarios_usuario USING btree (rol_id);


--
-- Name: usuarios_usuario_user_permissions_permission_id_4e5c0f2f; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_user_permissions_permission_id_4e5c0f2f ON public.usuarios_usuario_user_permissions USING btree (permission_id);


--
-- Name: usuarios_usuario_user_permissions_usuario_id_60aeea80; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_user_permissions_usuario_id_60aeea80 ON public.usuarios_usuario_user_permissions USING btree (usuario_id);


--
-- Name: usuarios_usuario_username_be9def2b_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX usuarios_usuario_username_be9def2b_like ON public.usuarios_usuario USING btree (username varchar_pattern_ops);


--
-- Name: ventas_detalleventa_producto_id_a820c807; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ventas_detalleventa_producto_id_a820c807 ON public.ventas_detalleventa USING btree (producto_id);


--
-- Name: ventas_detalleventa_venta_id_c370bcd7; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ventas_detalleventa_venta_id_c370bcd7 ON public.ventas_detalleventa USING btree (venta_id);


--
-- Name: ventas_venta_cliente_id_85f33a80; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ventas_venta_cliente_id_85f33a80 ON public.ventas_venta USING btree (cliente_id);


--
-- Name: ventas_venta_cliente_id_85f33a80_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ventas_venta_cliente_id_85f33a80_like ON public.ventas_venta USING btree (cliente_id varchar_pattern_ops);


--
-- Name: ventas_venta_usuario_id_a710a973; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ventas_venta_usuario_id_a710a973 ON public.ventas_venta USING btree (usuario_id);


--
-- Name: api_reporteproductosvendidos api_reporteproductos_reporte_id_de23fe7a_fk_api_repor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.api_reporteproductosvendidos
    ADD CONSTRAINT api_reporteproductos_reporte_id_de23fe7a_fk_api_repor FOREIGN KEY (reporte_id) REFERENCES public.api_reporte(id_reporte) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auditoria_auditlog auditoria_auditlog_usuario_id_10036f54_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auditoria_auditlog
    ADD CONSTRAINT auditoria_auditlog_usuario_id_10036f54_fk_usuarios_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_usuarios_usuario_id FOREIGN KEY (user_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_producto productos_producto_categoria_id_1fef506a_fk_api_categ; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_producto
    ADD CONSTRAINT productos_producto_categoria_id_1fef506a_fk_api_categ FOREIGN KEY (categoria_id) REFERENCES public.api_categoria(id_categoria) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_producto productos_producto_creado_por_id_6ad29e0b_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_producto
    ADD CONSTRAINT productos_producto_creado_por_id_6ad29e0b_fk_usuarios_ FOREIGN KEY (creado_por_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: productos_producto productos_producto_editado_por_id_4818f191_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.productos_producto
    ADD CONSTRAINT productos_producto_editado_por_id_4818f191_fk_usuarios_ FOREIGN KEY (editado_por_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_groups usuarios_usuario_gro_usuario_id_7a34077f_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_gro_usuario_id_7a34077f_fk_usuarios_ FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_groups usuarios_usuario_groups_group_id_e77f6dcf_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_groups
    ADD CONSTRAINT usuarios_usuario_groups_group_id_e77f6dcf_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario usuarios_usuario_rol_id_b0d64932_fk_usuarios_rol_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario
    ADD CONSTRAINT usuarios_usuario_rol_id_b0d64932_fk_usuarios_rol_id FOREIGN KEY (rol_id) REFERENCES public.usuarios_rol(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_use_permission_id_4e5c0f2f_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_use_permission_id_4e5c0f2f_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: usuarios_usuario_user_permissions usuarios_usuario_use_usuario_id_60aeea80_fk_usuarios_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usuarios_usuario_user_permissions
    ADD CONSTRAINT usuarios_usuario_use_usuario_id_60aeea80_fk_usuarios_ FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_detalleventa ventas_detalleventa_producto_id_a820c807_fk_productos; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ventas_detalleventa
    ADD CONSTRAINT ventas_detalleventa_producto_id_a820c807_fk_productos FOREIGN KEY (producto_id) REFERENCES public.productos_producto(id_producto) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_detalleventa ventas_detalleventa_venta_id_c370bcd7_fk_ventas_venta_id_venta; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ventas_detalleventa
    ADD CONSTRAINT ventas_detalleventa_venta_id_c370bcd7_fk_ventas_venta_id_venta FOREIGN KEY (venta_id) REFERENCES public.ventas_venta(id_venta) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_venta ventas_venta_cliente_id_85f33a80_fk_clientes_clientes_cedula; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ventas_venta
    ADD CONSTRAINT ventas_venta_cliente_id_85f33a80_fk_clientes_clientes_cedula FOREIGN KEY (cliente_id) REFERENCES public.clientes_clientes(cedula) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ventas_venta ventas_venta_usuario_id_a710a973_fk_usuarios_usuario_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ventas_venta
    ADD CONSTRAINT ventas_venta_usuario_id_a710a973_fk_usuarios_usuario_id FOREIGN KEY (usuario_id) REFERENCES public.usuarios_usuario(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict sUiV8wzXisFiQegOiQnnPSXlOz8EREWX6CCBeqVbIHhI0PadrZyfOGfLV65lvxv

