services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: florsync123
      POSTGRES_DB: FlorsyncBD
      SUPABASE_URL: https://fhnookveztdjpygotqpp.supabase.co
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZobm9va3ZlenRkanB5Z290cXBwIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3MTk4OTgwMiwiZXhwIjoyMDg3NTY1ODAyfQ.r1MSy5utXVwPEnKKoIJXQzUFd6N7okbNxRYvDYjBVCQ
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./wal-archive:/wal-archive
    command: >
      postgres
      -c wal_level=replica
      -c archive_mode=on
      -c archive_command='bash /wal-archive/archive.sh %p %f'
  backend:
    build: ./florsync_backend  
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://floruser:florsync123@db:5432/FlorsyncBD  
    ports:
      - "8000:8000"
    volumes:
      - ./florsync_backend:/app  
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build: ./florsync_frontend  
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./florsync_frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  postgres_data: {}