# Generated by Django 5.1.4 on 2026-02-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_total_alter_detalleventa_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='efectivo_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
