# Generated by Django 5.1.4 on 2026-02-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_categoria_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
    ]
