# Generated by Django 5.1.4 on 2026-02-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_detalleventa_producto_delete_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
