# Generated by Django 5.1.4 on 2026-02-12 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_clientes_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
