# Generated by Django 5.1.4 on 2026-04-07 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
