# Generated by Django 5.1.4 on 2026-02-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='objeto_nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
