# Generated by Django 5.1.4 on 2026-03-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_auditlog_objeto_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='objeto_id',
            field=models.CharField(max_length=50),
        ),
    ]
