# =========================
# WAL / REPLICATION
# =========================

wal_level = replica

archive_mode = on

archive_command = 'test ! -f /var/lib/postgresql/wal_archive/%f && cp %p /var/lib/postgresql/wal_archive/%f'

restore_command = 'cp /var/lib/postgresql/wal_archive/%f %p'

archive_timeout = 60


# =========================
# RECOMMENDED STABILITY SETTINGS
# =========================

max_wal_size = 1GB
min_wal_size = 256MB

wal_keep_size = 512MB


# =========================
# RECOVERY BEHAVIOR
# =========================

recovery_target_action = 'promote'
recovery_target_timeline = 'latest'
recovery_target = 'immediate'